### PR TITLE
Exceptions instead of print + tests

### PR DESCRIPTION
**Pull request by masell**
Added unittests
Instead of print, use exceptions.

you can run with:
`python -m unittest discover test/`

### CODE REVIEW

**Comment by RobbyB97** [comment]
Hey, I merged into master. Working on integrating the tests with the newer version. It returns errors on test_channel and test_invalid_links, but the functions its testing do work. The changes made to the yt.py file do work as intended. If you'd like to take another look at it, it would be appreciated!

**Comment by masell** [comment]
@RobbyB97 What branch/tag are you on? What is the cmd you use and what is the output?

On current master:
`python -m unittest discover test/`

```
...yt.video - Error! Not a valid link.
....
----------------------------------------------------------------------
Ran 7 tests in 0.004s

OK
```


The Error! above is from logging from https://github.com/RobbyB97/yt-iframe-python/blob/master/yt_iframe/yt_iframe/yt.py#L64 andcan be silenced if you configure the logging.

**Comment by RobbyB97** [comment]
I'm on the v1.0.2 branch... I see why they should be on master lol

**Comment by masell** [comment]
So, you changed the return value for `channel` function?
In master it's a list of "iframe" string, while in v1.0.2 it's a list of the urls.

When changing the return values like this, you should really follow [semver](https://semver.org/).
As this is a API breaking change the MAJOR version number needs to go up. so, this should be v2.0.0, not v1.0.2.

Now, as this is not merged into master, there are no tags, (only branches..) i don't know what version this was introduced. bisection is impossible.

If you want to fix it, update the test case https://github.com/RobbyB97/yt-iframe-python/blob/v1.0.2/yt_iframe/test/test_channel.py#L22 to something like this:
```
expected = ['https://www.youtube.com/embed/dQw4w9WgXcQ']
```

\- "I see why they should be on master lol" 
Then why don't you merge it? Master does NOT need to always be build-able / deploy-able. There are releases for this. In git you can also simply add a tag for the commit that is the HEAD of the release "v1.0.2". You are currently using branches for this.

**Pull request merged**
